const express = require('express');
const router = express.Router();
const multer = require('multer');
const path = require('path');
const { verifyToken, checkRole } = require('../middleware/authMiddleware');
const controller = require('../controllers/simpleInstallationController');

const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        cb(null, 'uploads/');
    },
    filename: (req, file, cb) => {
        // Use exactly the timestamp generated by frontend if available, or generate a unique name
        const prefix = req.body.timestamp || Date.now();
        cb(null, `${prefix}-${file.originalname.replace(/[^a-zA-Z0-9.\-]/g, '_')}`);
    }
});
const upload = multer({ storage });

const uploadFields = upload.fields([
    { name: 'photos', maxCount: 15 },
    { name: 'photoHuep', maxCount: 1 },
    { name: 'photoModem', maxCount: 1 },
    { name: 'photoOtdr', maxCount: 1 },
    { name: 'signature', maxCount: 1 }
]);

router.use(verifyToken);
router.post('/', uploadFields, controller.createInstallation);
router.get('/', checkRole(['ADMIN', 'SUPER_ADMIN']), controller.getInstallations);

module.exports = router;
