const express = require('express');
const router = express.Router();
const multer = require('multer');
const path = require('path');
const { verifyToken, checkRole } = require('../middleware/authMiddleware');
const controller = require('../controllers/simpleInstallationController');

const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        cb(null, 'uploads/');
    },
    filename: (req, file, cb) => {
        // Use exactly the timestamp generated by frontend if available, or generate a unique name
        const prefix = req.body.timestamp || Date.now();
        cb(null, `${prefix}-${file.originalname.replace(/[^a-zA-Z0-9.\-]/g, '_')}`);
    }
});
const upload = multer({ storage });

router.use(verifyToken);
router.post('/', upload.array('photos', 15), controller.createInstallation);
router.get('/', checkRole(['ADMIN', 'SUPER_ADMIN']), controller.getInstallations);

module.exports = router;
