name: Deploy to Digital Ocean

on:
  push:
    branches: [ "master" ] # Se ejecutará al hacer git push a la rama master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e
            echo "0. Limpiando espacio en disco (Docker)..."
            docker system prune -f || true
            cd /root/app
            
            echo "1. Descargando codigo de Github..."
            git fetch origin master
            git reset --hard origin/master
            
            echo "2. Reconstruyendo contenedores Docker..."
            docker compose down
            docker compose up -d --build
            
            echo "3. Esperando estabilización del sistema (15s)..."
            sleep 15
            
            echo "4. Actualizando Base de Datos de Prisma..."
            docker compose exec -T server npx prisma db push
            
            echo "DESPLIEGUE FINALIZADO"
